// Define traducciones de funciones relacionadas con caracteres en español.

#define esAlfabetico isAlpha                   // Función para verificar si un carácter es alfabético (equivalente a isAlpha)
#define esAlfanumerico isAlphaNumeric          // Función para verificar si un carácter es alfanumérico (equivalente a isAlphaNumeric)
#define esAscii isAscii                        // Función para verificar si un carácter es un carácter ASCII (equivalente a isAscii)
#define esControl isControl                    // Función para verificar si un carácter es un carácter de control (equivalente a isControl)
#define esDigito isDigit                       // Función para verificar si un carácter es un dígito (equivalente a isDigit)
#define esGrafico isGraph                      // Función para verificar si un carácter es un carácter imprimible (equivalente a isGraph)
#define esDigitoHexadecimal isHexadecimalDigit // Función para verificar si un carácter es un dígito hexadecimal (equivalente a isHexadecimalDigit)
#define esMinuscula isLowerCase                // Función para verificar si un carácter es minúscula (equivalente a isLowerCase)
#define esImprimible isPrintable               // Función para verificar si un carácter es imprimible (equivalente a isPrintable)
#define esSignoDePuntuacion isPunct            // Función para verificar si un carácter es un signo de puntuación (equivalente a isPunct)
#define esEspacio isSpace                      // Función para verificar si un carácter es un espacio en blanco (equivalente a isSpace)
#define esMayuscula isUpperCase                // Función para verificar si un carácter es mayúscula (equivalente a isUpperCase)
#define esEspacioEnBlanco isWhitespace         // Función para verificar si un carácter es un espacio en blanco (equivalente a isWhitespace)